### ISSUE TITLE
Code Review Assignment #2

### ISSUE THREAD

**Issue by goktugerce** [bounswe/bounswe2015group8#300]
Please do a code review on the e8ec76c22e6946f8af7a7701f854d61d053a56ec commit until midnight today.

**Comment by gokcantali** [comment]
First of all, thank you for your contributions with this commit. You managed to implement plenty of functionality, good job!

Now, I would like to talk about some issues/suggestion regarding this piece of code:

##### *Clarity:* 
Your code is mostly clear and its readability is high for people who have experience with back-end programming. Yet, there are some minor issues which might cause some confusion among those who are unfamiliar with our project.
  *  Some of the variable names are too short. For example, you used 'm' for a Member object and 'p' for a Post object in a couple API functions. Even though we understand it easily, it might be hard for other people outside our group to keep track of these variables. Little longer variable names can be used there.
  *  The function names and their mapping URL names are different for some functions. Of course, this is your design choice and I can't argue with that. But for example, 'getById' function requires the mapping '/api/getHeritageById' so when people first look at the function, they might have a hard time understanding what the function returns. Even if you don't make them exactly that same, it would be better to use more accurate function names for the mapping URL.

Other than these, your code is really clear. 

##### *Bugs and Some Missing Features:*
There doesn't seem to be a major bug with your code, but I think a few so-called bugs exist in some places.
  *  The field 'owner' is not seen in the retrieved data from 'getPostById' API. This is mostly because you declared the owner field transient in the model. I believe you did that because it was raising exceptions. Yet, it would be better if you find a way to overcome this issue and retrieve this field too. (I don't know if you have already done that. If that's the case, just ignore this part)
  *  The above applies for the comments and the votes of a post too. (Again, ignore this if you have already fixed it)
  *  Sign Up API should check whether a user with the same username exists, and returns an error code if such user already exists. This sounds more likely a missing feature, but if a guest user tries to create an account with an already existing username, the project might raise an exception. So, consider this a minor bug.

These are some minor issues which you can solve easily. In addition there are some features that, I think, should be in the system.
  *  An API for getting the heritages of a post. This might be useful once we connect a post with more heritages.
  *  An API for editing a post. (If you have done that, you can ignore this one)
  * Default constructor is missing in PostApiModel. Even though it might be necessary, it would be better to include it.

But it would be better to talk to the Android team for more suggestions and details regarding the API.   
##### *Conventions*
I see that you are following a coding convention most of the time but I want to talk about some points.

   **1 - Variable Names:** I realize that you are using the classic Java convention for the variable names, starting with lower case and capitalize the initial letter of the words if there are more than one word in a variable name. Since you are following a convention and use it throughout the whole commit, this is good practice! But regarding static variables, I saw some inconsistent convention. In the 'ErrorCodes' interface, static variables are composed of only upper case letters and underscores between words. However, Utility classes, there are some static variables which follow the same convention as non-static variables. I think it would be better to use a standard for them too, but this is a minor thing.

  **2 - Indentation:** Your indentation is good and consistent. This significantly increases readability.

  **3 - Comments:** Even though your code is mostly self-explanatory, it needs more comments at some places. Especially where you are using external library calls (such as Gson or PasswordEncoder) you need to add comments so the reader can understand what to expect from that line. You can add a comment explaining what the functions take as input and what it returns.

  **4 - API Conventions:** I have seen that you used POST method for all API calls. However, I believe this is not appropriate for REST API convention. In this convention, creating requires POST, editing requires PUT and retrieving requires GET methods. Therefore, it would be better if retrieve-based API calls (such as getPostsByHeritageId) are called via GET method instead of POST method. The other API calls (create/insert based) should stay as POST.

##### *Documentation:*
Your code, although being pretty clear, still needs documentation for the sake of others to understand. Up until now, none of us focused on the documentation of the code, because we gave our attention to the features and functionalities of our project. Nevertheless, from now on we need to add documentation as well as implementation. Therefore, the following items are not only for you to follow, but for all of us:
  *  Each function we write should include a documentation with at least the following items:

     **1 - Parameters of the function:** Each parameter of the function should be documented right before the function (or right after the declaration, based on the documentation tool) The documentation regarding a function parameter shall at least include the variable name, the variable type and what the parameter's role is. 

     **2 - Return variable of the function:** The documentation also shall include what the return type of a function is, and what role the returning element has. In other words, what does the returning variable store? What is its role?

  *  Classes also should be documented and in the documentation, we should explain why we need this class and what it is used for.
  * I encourage everyone to use Doxygen as a documentation tool. Since we used it last semester, we are kind of used to it.

##### *Test Coverage:*
Even though your code does not seem to produce a serious bug, it still needs to be tested. An unfortunately, there is no test written for your methods. This does not only apply to you, none of us has written unit tests until now. But from now on, every one of us must include unit tests with our implementation. 
Now, just in case you struggle with idea of how to apply unit tests to your code, I have some test suggestions for you:
  * For retrieve-based API calls (the ones that usually start with 'get'), you can first create an instance without using the API, and add it to the database via Hibernate. Then, you can try to retrieve the item using the API, and compare the fields of the retrieved object with the one you created. If all fields match, the test is considered a success.
  * For insert-based API calls (the ones that usually start with 'post' or 'create'), first create an instance using the API call, and then retrieve it from the database using Hibernate, without the API. Then, compare all the fields and consider it a success if all fields match.

The non-API functions are easier to test I believe. Just like what we did in the previous course, you can just try to call the function, and based on what you are expecting it to return and what it actually returns, consider it a success or not.

##### *Modification Suggestion:*
Some of your methods can become shorter and for that, I would like to suggest a modification on a part of the commit.
For example, consider the below code piece you wrote in "HeritageApi.java":

    public String getPostById(@RequestBody int id) {
        ArrayList<Post> posts = HeritageUtility.getPostList();
        for (Post p : posts) {
            if (p.getId() == id) {
                return gson.toJson(p);
            }
        }
        return Integer.toString(POST_DOES_NOT_EXIST);
    }

Here, you are selecting every post object from the database and iterate over them to check which one has the requested id. Even though this will work as intended, it has some problems. Using this approach not only lengthens the amount of code you have to write, but also causes the application to consume more RAM. Right now, when we have a few number of records in our database, it is fine. But, if our database gets larger, it will cause some serious performance issues. So, instead of getting all the records into the application, you can filter the records in Database level, and get only the requested record. Let's say you have a function called 'getPostById' which performs just what I said. Then, your code becomes like this:

    public String getPostById(@RequestBody int id) {
        Post post = HeritageUtility.getPostById(id);
        if(post != null)
            return gson.toJson(p);
        }
        return Integer.toString(POST_DOES_NOT_EXIST);
    }

This is both a cleaner and shorter code to use.

##### *Construct Styles:*
I also want to talk briefly about your construct styles. 
  +  **Loops:** I like the way you use for loops. You used them as 'foreach' instead of regular for loops and we don't have to keep track of the index. Although, I suggest you to use a longer name for iterating variables.
  +  **Classes:** You have many classes and it seems that they are layered. It is really good that you use layered architecture, since it is a good practice of Object-Oriented Programming.
  +  **Functions:** You use the same convention for functions, the same one you use for the non-static variables. Good job preserving your convention along the way!

Lastly, I suggest you to use IntelliJ's code inspector. It detects even typos and other minor things that we usually choose to ignore. But since we are using IntelliJ anyway, it would be a good idea to use it before you commit your code.

In overall, this was a good commit and I believe you will contribute even better commits in the future. Keep up the good work!

**Comment by goktugerce** [comment]
Thank you for all your sincere comments and detailed review, Gökcan! I didn't expect any less from you, though. Good work as always.

By taking your recommendations into consideration, I have done several changes in the code. First of all, your modification suggestion was awesome and I have adapted to it. My code now looks much cleaner. I also added comments to all functions which would make anyone's life easier. I used Doxygen as documentation tool.

About your thoughts on GET and POST methods on API calls, I did what you suggested at first but our API users asked me to use POST on every API method, so I adapted to their suggestion.

Thank you again for your suggestions. It's a pleasure working with you.
