### ISSUE TITLE
Code Review Assignment

### ISSUE THREAD

**Issue by mrtysn** [bounswe/bounswe2015group8#301]
Please do a code review on 707dd901113add8d0cb772205bf9a414d860db2b by 23:59, December 12th.

**Comment by goktugerce** [comment]
Hello Mert,

Thank you for your contributions to our project. I would like to talk about some positives and negatives regarding your commit in which you revised heritage and post pages.

##### *HTML Practices:* 
To be able to review your code better, I have made research about how HTML code should be, and what are the best practices of it. I have written down some notes and I would like to review your code by following these notes.

  *  Number one rule in HTML is always closing the tags. I see that you always do that and this is a crucial point. Good job.

  *  I see that in your pages you declared DocType and that is a good point.

  *  I think you should consider stopping the use of inline styles. This is seen as a bad practice. When creating your markup, don't think about the styling yet. Instead, add styling once the page has been completely coded. For example:

    ```<body style="background-color: #265a88">```

    This is from your `header.jsp` page. It may look harmless but it would be better if you can write your styling inside a style tag.

  *  You have added all the external CSS files within the head tags, so there is no problem with that.

  *  In the `list_heritage.jsp` file, I think you should consider placing Javascript code at the bottom, before including `footer.jsp`. The primary goal is to make the page load as quickly as possible. In that case, loading the script doesn't take long but it is the best practice to keep them down just before the closing body tag.

  *  Just a simple rule of thumb, but you always keep your tag names lowercase, so it is all good.

  *  I think you also should not use inline Javascript. Instead, transfer those inline codes into the script tags before the closing body tag. You can also use <a href="http://jquery.com/">jQuery</a> for button click listeners, for example in the `list_heritage.jsp` file.

  *  Lastly, I have read that all images need `alt` attribute. Maybe you can add them to describe images.

I don't think your code needs a lot of time to refactor. Other than some simple points, there is not any mistakes within your code as far as I saw. Your indentation is excellent and that makes reading the page easier.

##### *Validation:* 
I do not know much about testing HTML code, but I searched for it and came across <a href="https://validator.w3.org/">Markup Validation Service</a>. Maybe you can check it and start using it to test/validate your markup. Are you validating your code continuously? This is considered as an excellent practice. As some guy said, _validation should work for you, not against._. I recommend you to take a look at <a href="https://addons.mozilla.org/en-US/firefox/addon/web-developer/">Web Developer Toolbar</a> and see if it is any good for you. Have you heard about <a href="https://addons.mozilla.org/en-US/firefox/addon/firebug/">Firebug</a>? It is a marvelous plugin to use when creating websites. It provides incredible Javascript debugging and it can even tell you about padding errors!

##### *Modification Suggestion:* 
As I have said, there are not many things in your code to be changed but I definitely suggest you to drop the use of inline styling and scripting and write them within the tags. 

I added some line comments in order to make your job easier. I may have missed some but you can <a href="https://github.com/bounswe/bounswe2015group8/pull/220/files#diff-a2ce101bb09a8eb2d59effa3736f74adR79">check them here</a>.

That is all from me, Mert. Thank you for your awesome contributions to our project and hope to see the same from you during our last month.

Best.

**Comment by mrtysn** [comment]
Hi Göktuğ,

First of all, thanks for the wonderful suggestions. I'd like to address a few of them.

Moving javascript codes to the end of file is actually a great suggestion since it would drop the render time significantly. We should apply this practice to our project globally. I'll be changing that.

The front-end team is aware that in-line styling is a bad practice. We keep a separate styling file for the global changes. However in those files stated above, there are some minor styling predicates and they need not be in a global manner. Altough it is still arguable to do it both ways, I believe it is more efficient to keep them as is.

There are some actions that are both possible with JavaScript and JQuery, in the end they are really small measures. Sometimes it is better to choose one sometimes the other. Modifying those statements are not necessary as well at this stage of the project.

I'll be making the modifications stated above in a short notice.

Thank you for your time!
