### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by bugrahan** [bounswe/bounswe2015group8#303]
Please do a code review of my c913f8c commit until midnight.

**Comment by berksalmanoglu** [comment]
Thank you for creating our login and register pages on android! here are my opinions:

-Code Clarity:
The code is simple and clear. I did not have hard times reading and understanding your code eventhough I do not have many experiences with android programming. Besides I believe it is clear for most of people who is interested in some programming languages.
There is only two lines of code which may not be clear for everybody, as listed below:

HttpPost post = new HttpPost(SERVER_ADDRESS + "Register.php");
HttpPost post = new HttpPost(SERVER_ADDRESS + "FetchUserData.php");

They are in ServerRequests.java and in my opinion they were used for testing some functionalities in the early stages of our project. You could specify or just delete these lines.

-Bugs and Some Missing Features:
I have not seen any bugs or missing features, it fulfilles all needs of login and register pages.

-Conventions
Your variables names are fine and purpose-specific, so that they helped me understanding what is going on on these commit.
There is no problem with indentation.
Eventhough they are simple login and register pages which explain themselves easily, there could be some comments in ServerRequests.java, as I mentioned above.

-Documentation
In programming, there is always a need for documentation eventhough we do not consider it necessary all the time. I have not documented my codes yet, as well. So, all of us eventually should start preparing our documentations in order to make others understand our code when they want to look and find out what is happening. You can at least start by pointing out what parameters your functions take and what they return.

-Test Coverage
Here is the same case with documentation. You should write testcases for your commits, although there does not seem to be any problems with these login and register pages.

-Modification Suggestion
I saw some repetitions in xml files. You can declare your styles in a single xml which you can use in further pages, not only in login and register pages, also in other pages.

-Construct Styles
I did not see any problems with the construct styles you used. They are just regular and necessary loops, classes and functions, which play their usual role in a login or register page.
