### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by siray** [bounswe/bounswe2015group8#305]
Please do a code review of my 72de790 commit until midnight.

**Comment by mrtysn** [comment]
The code is crystal clear, I've had no issues performing the review. Here are my observations.

In PostDaoImpl.java, the session is opened but not closed. Other than that, I couldn't spot any other bugs. All of the proposed features are present, thanks for that.

As for the coding convention, we can use longer variable names for example 'session' instead of 's', 'member' instead of 'm' since it increases readability in other parts of the code. I think we should convert all short variable names to longer ones. The indentation is as it should be however there might be some points which would be better of if commented. The code might seem to be self-explanatory but that's not the case for everyone. A short description of each method would be sufficient I suppose. Doxygen format is a suggestion for this purpose, we should decide as a group which format to use and document the code properly correlating with this decision.

For persistency concerns, there should be some unit tests, therefore we ought to add those. We could perform a simple HTTP.Post test where we pass a single integer, a comment test with a sample text and, an editing with another sample text.

I believe there would be no issue if I tried to modify to code. One modification I would propose is displaying a pop-up notification to user after a modified post. '/show_posts/heritageId' page might implement such a feature similar to the '/login' page. This would improve the user experience.

In addition, I've ran IntelliJ Code Analyzer on some parts of the code and there are no note-worthy suggestions.

Overall, thanks for your contribution.
