### ISSUE TITLE
Code reviews

### ISSUE THREAD

**Issue by berksalmanoglu** [bounswe/bounswe2015group8#307]
Please review my code on commit 905203230e4c72f9d97ade67784484ac51059d16

**Comment by tugceeskili** [comment]
###*Code Clarity:*
Code is mostly readable, and clear enough to comprehend.

###*Bugs:*
I couldn't find any bug related to your commit. Frontend may have an advantages at this point, any bug or failure can be easily detected while going over the each page to check whether they are implemented accurately or not. So, your code seems bug-free.

###*Missing Features:*

There is no necessary feature that has not been done yet. Maybe later, some modifications will be needed related the general page design.

###*Coding Conventions:*

*Variable Names:
Since this is one of the frontend commits, it includes only php, html, javascript codes. Therefore variable names are not given by the developer, instead, they are compatible with general rules of html coding style.

*Indentation:
Thanks to IntelliJ, any indentation error is corrected according to Java's indentation guidelines.

*Comments:
Here a few suggestion for optimization, on list_post and list_heritages pages, you did authorization check with security tag for some button in order to prevent users who has not logged in yet to see them. Instead of doing these check for each one separately, you can add a new boolean variable on the top of the page, which does the same check, and for each button you need to check only the value of the variable with if - else method. Furthermore, you can add this variable on the header, and you won't have to define a new variable for each page. 

###*Incomplete Code Documentation:*

All of us have been focused on the features and functionalities of our project so we haven't done documentation yet. But still it is needed for others to understand the code.

###*Coverage with unit tests:*

There is no unit test for any method in any page. Since they are mostly html and javascript codes, they are untestable but what we can do may be going over each page. We can check the functionality of the buttons by directly pressing them see if they are works or not. That would be more likely a usability check.

###*Code Modification:*

Codes are easy to modify. If I want to reform the general view of tha page, I can handily resize the divisions or change the base color.

###*Construct style:*

All classes are coherent with HTML's, Spring's, and Java's guidelines. 

###*Code Analysis Tools:*

There has not been a significant suggestion given by the analyzer while running IntelliJ Code Analyzer on the codes that are included in the commit.

Generally your code is flawless, you did a great job, thanks for your unreplaceable contribution to our team project !
