### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by arslanbenzer** [bounswe/bounswe2015group8#308]
Please review code on commit [c1d510b](https://github.com/bounswe/bounswe2015group8/commit/c1d510bb8f3f82e48fafd2b822e8bc04a5a2b424)

**Comment by siray** [comment]
## Review of the commit  c1d510b ##
### *Code Clarity*
It is a very clear commit. Function and variable names are chosen openly and function goals are understandable.  

### *Bugs*
There is no major bug in this commit. At first, existence of both increment and decrement functions in getVoteCount() method seems as causing a bug in extreme cases but because we have also negative vote feature it is not a bug.

### *Missing Features*
It is written according to its features so there is no need a new big feature implementations. However, there should be some little improvements. Method can be kept both positive and negative vote values not only the vote result. So we can use this values while finding recommended posts. For example, there is a post with 5 upvote&3 downvote and 500 upvote&499 downvote. In this case, the second post should be recommended according to vote counts because more user see and vote the second one.

### *Coding Convention*
•	Variable Names: Variable names are clear.  Only one of them, in getVoteCount() method “cv” is not a good name in my opinion. I think this as initialism of count vote. Actually it is a variable on for loop so it is temporary, not important too much.

•	Indentation: Indentation is good enough.

•	Comments:There is no comments in this commit. Because it is a short and well explained it is okay, but at least before the function declarations there may be some comments.

### *Incomplete Code Documentation*
There is no code documentation. Functions are clear but it is need to be done anyway.

### *Coverage with Unit Tests*
There are no unit tests for any of the methods. Because of it is api side of the project unit tests should be check coherence between web and api sides not only the results.

### *Code Modification*
I can easily do a modification , for example I can add upvote and downvote values to  getVoteCount() method and and evaluate netCount value from these. 

### *Construct Style*
Classes are all compliant with Hibernate's, Spring's, and Java's guidelines. Methods are small and modular. 

### *Code Analysis Tools*
IntelliJ Code Analyzer don’t suggest any changes on the methods associated with the commit.

**Comment by siray** [comment]
Review is done
