### ISSUE TITLE
Editing A Post fails  for changing media

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group8#348]
I logged in as uskudarli
I edited the post "Searching for the Anastasian Wall" related to the heritage: Anastasian Wall.

I changed the strange photo with another one. Alas, it shows the old photo still. I tried twice.

It should show the newly added media
![img_0776](https://cloud.githubusercontent.com/assets/1347035/12130566/14e05f74-b414-11e5-88d4-c2afff2fefad.JPG)

The media file can't be scene. Only see attachment sign. So, there is no way to have an idea what image / if any is attached.

One could want to add many images. And images within the story, so it is clear what is associated with what.

Also, one could add images that are already on the web. Or videos on Youtube, Vimeo, etc.

(Adding URL in body of text shows the video so that is nice in a way)

I did not test if other updates work.

**Comment by gokcantali** [comment]
As we explained in issue #351, this bug should also be fixed since adding another media file is not a part of the edit form anymore. However, you should know that once a media file is added, it cannot be removed using the user interface. (similar to how our system does not allow deletion of posts/heritages/comments)

If you encounter this bug again, or something related to it, please let us know shorty afterwards.
